library/library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from hust_library import views

urlpatterns = [
    path('', views.index_view, name='index'),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.logout_then_login, name='logout'),
    path('is_admin/', views.is_admin_view, name='is_admin'),
    path('self_inf/', views.self_inf_view, name='self_inf'),
    path('loans/', views.loans_view, name='loans'),
    path('loaned/', views.loaned_view, name='loaned'),
    path('loaned/renew/<int:pk>', views.renew_view, name='renew'),
    path('tickets/', views.tickets_view, name='tickets'),
    path('tickets/handle/<int:pk>/',
         views.ticket_handle_view, name='ticket_handle'),
    path('books/', views.books_view, name='books'),
    path('books/<int:pk>/', views.BookView.as_view(), name='book'),
    path('administrator/', views.administrator_view, name='administrator'),
    path('administrator/books_manage/',
         views.books_manage_view, name='books_manage'),
    path('administrator/books_manage/<int:pk>/',
         views.book_manage_view, name='book_manage'),
    path('administrator/books_manage/new/',
         views.new_book_view, name='new_book'),
    path('administrator/books_manage/edit/<int:pk>/',
         views.edit_book_view, name='edit_book'),
    path('administrator/books_manage/delete/<int:pk>/',
         views.delete_book_view, name='delete_book'),
    path('administrator/books_manage/write/<int:book_pk>/',
         views.write_view, name='write'),
    path('administrator/books_manage/<int:book_pk>/write/new/',
         views.new_write_view, name='new_write'),
    path('administrator/books_manage/write/edit/<int:pk>/',
         views.edit_write_view, name='edit_write'),
    path('administrator/books_manage/write/delete/<int:pk>/',
         views.delete_write_view, name='delete_write'),
    path('administrator/books_manage/store/<int:book_pk>/',
         views.store_view, name='store'),
    path('administrator/books_manage/<int:book_pk>/store/new/',
         views.new_store_view, name='new_store'),
    path('administrator/books_manage/store/edit/<int:pk>/',
         views.edit_store_view, name='edit_store'),
    path('administrator/books_manage/store/delete/<int:pk>/',
         views.delete_store_view, name='delete_store'),
    path('administrator/readers_manage/',
         views.readers_manage_view, name='readers_manage'),
    path('administrator/readers_manage/<int:pk>/',
         views.reader_manage_view, name='reader_manage'),
    path('administrator/readers_manage/new/',
         views.new_reader_view, name='new_reader'),
    path('administrator/readers_manage/edit/<int:pk>/',
         views.edit_reader_view, name='edit_reader'),
    path('administrator/readers_manage/delete/<int:pk>/',
         views.delete_reader_view, name='delete_reader'),
    path('administrator/readers_manage/set_password/<int:pk>/',
         views.set_password_view, name='set_password'),
    path('administrator/borrow_manage/',
         views.borrow_manage_view, name='borrow_manage'),
    path('administrator/return_manage/',
         views.return_manage_view, name='return_manage')
]

library/hust_library/models.py
from django.db import models
from django.contrib.auth.models import User


class Ticket(models.Model):
    price = models.DecimalField(max_digits=6, decimal_places=2)
    time = models.DateTimeField()
    state = models.SmallIntegerField(default=0)
    description = models.CharField(max_length=150)
    reader = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="ticket_reader_id")

    def __str__(self):
        return self.description


class Book(models.Model):
    name = models.CharField(max_length=150)
    publish = models.CharField(max_length=150)
    time = models.IntegerField()
    price = models.DecimalField(max_digits=6, decimal_places=2)

    class Meta:
        unique_together = ("name", "publish", "time", "price")

    def __str__(self):
        return self.name


class Write(models.Model):
    writer = models.CharField(max_length=150)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    def __str__(self):
        return self.writer

    class Meta:
        unique_together = ("writer", "book")


class Store(models.Model):
    location = models.CharField(max_length=150)
    state = models.SmallIntegerField(default=1)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    def __str__(self):
        return self.location


class Loan(models.Model):
    time = models.DateTimeField()
    state = models.SmallIntegerField(default=0)
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    reader = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="loan_reader_id")

library/hust_library/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from . import models


class BorrowManageForm(forms.Form):
    store_id = forms.IntegerField(label='藏书号')
    username = forms.CharField(label='用户名', max_length=150)


class ReturnManageForm(forms.Form):
    store_id = forms.IntegerField(label='藏书号')
    is_broken = forms.BooleanField(label='书籍损坏', required=False)


class BookForm(forms.ModelForm):
    class Meta:
        model = models.Book
        fields = ['name', 'publish', 'time', 'price']
        labels = {
            'name': _('书名'),
            'publish': _('出版社'),
            'time': _('出版时间'),
            'price': _('价格')
        }


class ReaderForm(forms.Form):
    username = forms.CharField(label='用户名', max_length=150)
    last_name = forms.CharField(label='姓', max_length=150)
    first_name = forms.CharField(label='名', max_length=30)
    email = forms.EmailField(label='邮箱')

library/templates/administrator.html
{% extends "base.html" %}
{% load static %}
{% block lead %}
<nav class="navbar navbar-expand-md navbar-dark bg-primary">
    <div class="container">
        <div class="collapse navbar-collapse" id="navbar18">
            <a class="navbar-brand d-none d-md-block" href="{% url 'index' %}">
                <b> 华中科技大学图书馆</b>
            </a>
            <ul class="navbar-nav mx-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown"> 图书管理 </a>
                    <div class="dropdown-menu bg-primary ">
                        <a class="dropdown-item text-light" href="{% url 'books_manage' %}">搜索书籍</a>
                        <a class="dropdown-item text-light" href="{% url 'new_book' %}">新建书籍</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown"> 读者管理 </a>
                    <div class="dropdown-menu bg-primary ">
                        <a class="dropdown-item text-light" href="{% url 'readers_manage' %}">搜索读者</a>
                        <a class="dropdown-item text-light" href="{% url 'new_reader' %}">新建读者</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown"> 借阅管理 </a>
                    <div class="dropdown-menu bg-primary ">
                        <a class="dropdown-item text-light" href="{% url 'borrow_manage' %}">借书</a>
                        <a class="dropdown-item text-light" href="{% url 'return_manage' %}">还书</a>
                    </div>
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-light" href="#" id="navbardrop" data-toggle="dropdown">
                        {% if request.user.is_authenticated %}
                        {{ request.user.username }} 您好
                        {% else %}
                        欢迎
                        {% endif %}
                    </a>
                    <div class="dropdown-menu bg-primary ">
                        {% if request.user.is_authenticated %}
                        <a class="dropdown-item text-light" href="{% url 'logout' %}">登出</a>
                        {% else %}
                        <a class="dropdown-item text-light" href="{% url 'login' %}">登录</a>
                        {% endif %}

                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% endblock %}
{% block content %}
<div class="py-5">
    <div class="container">
        <div class="row">
            <div class="mx-auto col-md-9">
                <h1 class="mb-3 text-center">本馆介绍</h1>
                <p>&nbsp; &nbsp; 华中科技大学图书馆现设主馆、医学分馆、东区分馆三个馆区，馆舍总面积64581平方米，各类阅览室33个，可用座位6500多个，其中电子阅览室3个，计算机近300台。</p>
                <h3 class="mb-3">文献信息资源体系建设</h3>
                <p>&nbsp; &nbsp;
                    图书馆积极服务华中科技大学的建设和发展，大力加强文献信息资源体系建设，优先发展电子资源，适度发展印刷资源。馆藏文献涵盖理、工、医、文、管等九大学科门类。&nbsp;&nbsp;<br>&nbsp;
                    &nbsp; 截至2017年12月31日，馆藏文献总量为1045.98万册。医学古籍特藏是馆藏特色之一，三种古籍入选《国家珍贵古籍名录》。&nbsp;<br>&nbsp; &nbsp;
                    现有中、外文数据库577个，数据库总量在全国高校名列前茅。一批高水平数据库为学校教学、科研和学科建设提供了强大的文献信息保障。</p>
                <h3 class="mb-3" style="">文献信息服务体系建设</h3>
                <p>&nbsp; &nbsp; 为服务好学校改革发展和学科需要，近年来，图书馆着力建设文献信息服务体系，拓宽知识服务边界，取得了良好效果。&nbsp;&nbsp;<br>&nbsp; &nbsp;
                    依托丰富的馆藏资源和专业人才优势，图书馆开展了以职能部门和院系需求为目标，以决策支持服务和特色学科服务为中心的学科情报分析、定题及专利服务，为学校“双一流”建设当好科技情报的“千里眼”“顺风耳”。&nbsp;&nbsp;<br>&nbsp;
                    &nbsp; 图书馆还为全校师生提供信息检索教学、科技查新、馆际互借与文献传递等多种形式的专题服务，面向全校各院系、各学科、各大科学平台开展了有针对性的学科服务，服务对象已延伸到校外。</p>
                <h3 class="mb-3">校园文化建设</h3>
                <p>&nbsp; &nbsp;
                    除做好各项读者服务基础工作外，图书馆还不断拓展和深化服务，积极参与学校人才培养、信息化建设和校园文化建设。馆舍空间和多媒体空间、视频播放系统、高清视听室、学术报告厅等独特资源全年向院系和师生开放，学术大咖、科学前沿报告，高雅艺术、主题展览，精选好书、优选视频纷纷走进图书馆，与青年学子面对面。2014年开始打造的“一本好书，与你同行”系列阅读推广活动深受学生喜爱，2017年世界读书日专题活动“琅琅读书声”在第二届高校图书馆阅读推广案例大赛上荣获二等奖。
                </p>
                <h3 class="mb-3">“智慧化”图书馆建设</h3>
                <p>&nbsp; &nbsp;
                    随着学校的快速发展，师生读者对泛在服务的需求越来越迫切，传统图书馆变身智慧图书馆已是大势所趋。近年来，图书馆不断加强数字化基础工作，致力于“智慧化”的探索。除广为人知的无线射频识别系统（RFID）等数字化系统外，创新性地建设了网络安全多维度防护、业务大数据平台、自建数据私有云、手机借还、读者蓝牙物联、高精度三维导航等特有的服务与应用平台，确保数据有容量、安全有保障、服务有智能、读者有感知，初步实现了“智慧化”图书馆的雏形。
                </p>
                <p>&nbsp; &nbsp; 秉承“读者第一，服务育人”的办馆宗旨，图书馆在华中科技大学双一流的征程中，正向着一流研究型图书馆的目标努力奋进！</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

library/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>华中科技大学图书馆</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.bootcss.com/bootstrap-table/1.14.2/bootstrap-table.min.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        type="text/css">
    <link rel="stylesheet" href="{% static 'css/theme.css' %}" type="text/css">
    <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap-table/1.14.2/bootstrap-table.min.js"></script>

    <style>
        .dropdown-item:hover {
            background-color: transparent;
        }

        a:hover,
        a:focus {
            text-decoration: none;
        }

        .nav-tabs {
            border-bottom: 1px solid rgba(0, 0, 0, 0.1);
        }

        .nav-tabs .nav-link.active,
        .nav-tabs .nav-item.show .nav-link {
            color: #495057;
            background-color: transparent;
            border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(236, 236, 236, 1);
        }
    </style>
    {% if messages %}
    <script>
        {% for msg in messages %}
        alert('{{ msg.message }}');
        {% endfor %}
    </script>
    {% endif %}
</head>

<body style="background-color: rgba(0,0,0,0.1)">
    {% block lead %}

    <nav class="navbar navbar-expand-md navbar-dark bg-primary">
        <div class="container">
            <div class="collapse navbar-collapse" id="navbar18">
                <a class="navbar-brand d-none d-md-block" href="{% url 'index' %}">
                    <b> 华中科技大学图书馆</b>
                </a>
                <ul class="navbar-nav mx-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'books' %}"> 图书信息</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tickets' %}"> 罚单信息</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown"> 借阅信息 </a>
                        <div class="dropdown-menu bg-primary ">
                            <a class="dropdown-item text-light" href="{% url 'loans' %}">借书记录</a>
                            <a class="dropdown-item text-light" href="{% url 'loaned' %}">待还书籍</a>
                        </div>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-light" href="#" id="navbardrop" data-toggle="dropdown">
                            {% if request.user.is_authenticated %}
                            {{ request.user.username }} 您好
                            {% else %}
                            欢迎
                            {% endif %}
                        </a>
                        <div class="dropdown-menu bg-primary ">
                            {% if request.user.is_authenticated %}
                            <a class="dropdown-item text-light" href="{% url 'self_inf' %}">个人信息</a>
                            <a class="dropdown-item text-light" href="{% url 'logout' %}">登出</a>
                            {% else %}
                            <a class="dropdown-item text-light" href="{% url 'login' %}">登录</a>
                            {% endif %}

                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% endblock %}

    {% block content %}
    {% endblock %}

</body>

</html>

library/templates/book.html
{% extends "base.html" %}

{% block content %}
<div class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-12" style="">
                <h2>图书信息</h2>
                <hr class="mb-4">
            </div>
        </div>
        <div class="row">
            <div class="p-3 col-md-8">
                <table class="table table-bordered table-hover table-striped">
                    <tbody>
                        <tr>
                            <th scope="row">编号</th>
                            <td>{{ book.id }}</td>
                        </tr>
                        <tr>
                            <th scope="row">书名</th>
                            <td>{{ book.name }}</td>
                        </tr>
                        <tr>
                            <th scope="row">作者</th>
                            <td>
                                {% for write in book.write_set.all %}
                                {{ write.writer }}
                                {% endfor %}
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">出版社</th>
                            <td>{{ book.publish }}</td>
                        </tr>
                        <tr>
                            <th scope="row">出版时间</th>
                            <td>{{ book.time }}</td>
                        </tr>
                        <tr>
                            <th scope="row">定价</th>
                            <td>{{ book.price }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-12">
                <h3>馆藏书籍</h3>
                <hr class="mb-4">
            </div>
        </div>
        {% if book.store_set.all.count == 0 %}
        <div class="row">
            <div class="col-md-12">
                <h4> 没有馆藏 </h4>
            </div>
        </div>
        {% else %}
        <div class="row">
            <div class="col-md-12">
                <div class="col-md-8 p-3">
                    <table class="table table-hover table-striped table-bordered">
                        <thead class="thead-inverse">
                            <tr>
                                <th scope="col">编号</th>
                                <th scope="col">馆藏地点</th>
                                <th scope="col">状态</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for store in book.store_set.all %}
                            <tr>
                                <td>{{ store.id }}</td>
                                <td>{{ store.location }}</td>
                                <td>
                                    {% if store.state == 0 %}
                                    借出
                                    {% elif store.state == 1 %}
                                    在馆
                                    {% else %}
                                    损坏
                                    {% endif %}
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

library/templates/books.html
{% extends "base.html" %}

{% block content %}
<div class="py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <form class="form-inline" action="{% url 'books' %}" method="get">
                    <div class="input-group">
                        <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Search"
                            name="name" required>
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% if 'name' in request.GET %}
<div class="py-4">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2>搜索结果</h2>
                <hr>
                {% if is_empty %}
                <p class="lead">搜索无结果</p>
                {% endif %}
                {% for book in books %}
                <a href="{% url 'book' book.id %}">
                    <p class="lead">{{ book.name }}</p>
                </a>
                <p>
                    作者：
                    {% for write in book.write_set.all %}
                    {{ write.writer }}
                    {% endfor %}
                    出版社：{{ book.publish }} 出版时间：{{ book.time }}
                </p>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

library/templates/borrow_manage.html
{% extends "administrator.html" %}

{% block content %}
<div class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2>借阅书籍</h2>
                <hr class="mb-4">
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                <form method="post" action="{% url 'borrow_manage' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>藏书号</label>
                        <input type="number" name="store_id" required class="form-control">
                    </div>
                    <div class="form-group">
                        <label>用户名</label>
                        <input type="text" name="username" maxlength="150" required class="form-control">
                    </div>
                    <button type="submit" class="btn btn-primary">借阅</button>
                </form>
            </div>
        </div>

    </div>
</div>
{% endblock %}

library/templates/login.html
{% extends "base.html" %}

{% block content %}

<div class="py-5 text-center" style="">
    <div class="container">
        <div class="row">
            <div class="mx-auto col-md-6 col-10 bg-white p-5">
                <h1 class="mb-4">Log in</h1>
                <form method="post" action="{% url 'login' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Username" required name="username">
                    </div>
                    <div class="form-group mb-3">
                        <input type="password" class="form-control" placeholder="Password" required name="password">
                    </div>
                    {% if form.errors %}
                    <p>Your username and password didn't match. Please try again.</p>
                    {% endif %}

                    {% if next %}
                    {% if user.is_authenticated %}
                    <p>Your account doesn't have access to this page. To proceed,
                        please login with an account that has access.</p>
                    {% else %}
                    <p>Please login to see this page.</p>
                    {% endif %}
                    {% endif %}
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <input type="hidden" name="next" value="{{ next }}">
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

library/templates/new_book.html
{% extends "administrator.html" %}

{% block content %}
<div class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2>新建书籍</h2>
                <hr class="mb-4">
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                <form method="post" action="{% url 'new_book' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>书名</label>
                        <input type="text" name="name" maxlength="150" required class="form-control">
                    </div>
                    <div class="form-group">
                        <label>出版社</label>
                        <input type="text" name="publish" maxlength="150" required class="form-control">
                    </div>
                    <div class="form-group">
                        <label>出版时间</label>
                        <input type="number" name="time" required class="form-control">
                    </div>
                    <div class="form-group">
                        <label>价格</label>
                        <input type="number" name="price" step="0.01" required class="form-control">
                    </div>
                    <button type="submit" class="btn btn-primary">新建</button>
                </form>
            </div>
        </div>

    </div>
</div>

{% endblock %}

library/templates/new_reader.html
{% extends "administrator.html" %}

{% block content %}
<div class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2>新建读者</h2>
                <hr class="mb-4">
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                <form method="post" action="{% url 'new_reader' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>用户名</label>
                        <input type="text" name="username" maxlength="150" required class="form-control">
                    </div>
                    <div class="form-group">
                        <label>姓</label>
                        <input type="text" name="last_name" maxlength="150" required class="form-control">
                    </div>
                    <div class="form-group">
                        <label>名</label>
                        <input type="text" name="first_name" maxlength="30" required class="form-control">
                    </div>
                    <div class="form-group">
                        <label>邮箱</label>
                        <input type="email" name="email" required required class="form-control">
                    </div>
                    <button type="submit" class="btn btn-primary">新建</button>
                </form>
            </div>
        </div>

    </div>
</div>

{% endblock %}

library/templates/readers_manage.html
{% extends "administrator.html" %}

{% block content %}
<div class="py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <form class="form-inline" action="{% url 'readers_manage' %}" method="get">
                    <div class="input-group">
                        <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Username"
                            name="name" required>
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% if 'name' in request.GET %}
<div class="py-4">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2>搜索结果</h2>
                <hr>
                {% if is_empty %}
                <p class="lead">搜索无结果</p>
                {% endif %}
                {% for reader in readers %}
                <p class="lead">
                    <a href="{% url 'reader_manage' reader.id %}">
                        {{ reader.username }}
                    </a>
                    <a class="btn btn-outline-primary ml-4" href="{% url 'delete_reader' reader.id %}">删除</a>
                </p>
                <p>
                    姓:{{ reader.last_name }}
                    名:{{ reader.first_name }}
                    邮箱:{{ reader.email }}
                </p>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

library/templates/return_manage.html
{% extends "administrator.html" %}

{% block content %}
<div class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2>归还书籍</h2>
                <hr class="mb-4">
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                <form method="post" action="{% url 'return_manage' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>藏书号</label>
                        <input type="number" name="store_id" required class="form-control">
                    </div>
                    <div class="form-group">
                        <div class="form-check my-3">
                            <input class="form-check-input" type="checkbox" name="is_broken" id="id_is_broken"
                                value="on">
                            <label class="form-check-label" for="id_is_broken">书籍损坏</label>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">还书</button>
                </form>
            </div>
        </div>

    </div>
</div>
{% endblock %}

library/templates/self_inf.html
{% extends "base.html" %}

{% block content %}
<div class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2>个人信息</h2>
                <hr class="mb-4">
            </div>
        </div>
        <div class="row">
            <div class="p-3 col-md-8">
                <table class="table table-bordered table-hover table-striped">
                    <tbody>
                        <tr>
                            <th scope="row">用户名</th>
                            <td>{{ request.user.username }}</td>
                        </tr>
                        <tr>
                            <th scope="row">姓</th>
                            <td>{{ request.user.last_name }}</td>
                        </tr>
                        <tr>
                            <th scope="row">名</th>
                            <td>{{ request.user.first_name }}</td>
                        </tr>
                        <tr>
                            <th scope="row">邮箱</th>
                            <td>{{ request.user.email }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}